import Link from "next/link";

import { Container } from "@/components/layout/container";
import { Section } from "@/components/layout/section";
import { ArrowRightIcon } from "@/components/ui/icons";

/**
 * The four figures the band puts beside the copy. `value` is the headline
 * number; `label` finishes the sentence it starts.
 */
const stats = [
  {
    value: "244,000,000+ tonnes",
    label: "generated by Africa in 2025 and over 90% was disposed openly",
  },
  {
    value: "215,000+ workers",
    label:
      "contribute to 80-90% of waste collection and recycling in South Africa",
  },
  {
    value: "$8,000,000,000",
    label:
      "or more is untapped from Africa since only 4% is recycled when 70-80% is recyclable",
  },
  {
    value: "Less than 2%",
    label:
      "of waste collection systems in Africa apply smart tracking technology",
  },
] as const;

/**
 * "The broken waste management system in Africa" (Figma 3024:3632 desktop,
 * 3070:36864 mobile): the argument on the left, the four numbers that back it
 * on the right.
 *
 * Sits directly under the hero -- Figma draws it inside the same
 * `better-future-frame` -- so it carries no top rule of its own; the dark plate
 * is the separation.
 *
 * The stats stay a two-up grid at every width. Figma keeps them side by side on
 * phones too, and the numbers are short enough to hold at 375px.
 */
export function WasteCrisis() {
  return (
    <Section tone="tertiary" spacing="md" aria-labelledby="waste-crisis-heading">
      <Container className="flex flex-col gap-8 lg:flex-row lg:justify-center lg:gap-17.5">
        <div className="flex flex-col items-start gap-4 lg:w-115.5 lg:shrink-0">
          <h2
            id="waste-crisis-heading"
            className="font-display text-2xl font-semibold text-white lg:text-3xl"
          >
            The broken waste management system in Africa
          </h2>
          <p className="text-sm text-tertiary-50 lg:text-lg">
            Africa generates 244M tonnes of waste yearly, 90% goes to
            uncontrolled dumps, yet informal collectors who manage most of it
            remain invisible to governments, leaving institutions helpless when
            the system fails.
          </p>
          <Link
            href="/why-us"
            className="flex w-full items-center justify-between gap-4 px-2.5 py-2 text-sm text-tertiary-100 transition-colors hover:text-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white lg:text-lg"
          >
            Learn more about our vision
            <ArrowRightIcon className="size-5 shrink-0" />
          </Link>
        </div>

        <dl className="grid grid-cols-2 gap-x-9.5 gap-y-4 lg:w-149 lg:shrink-0">
          {stats.map((stat) => (
            <div key={stat.value} className="flex flex-col">
              <dt className="font-display text-xl font-semibold text-white lg:text-2xl">
                {stat.value}
              </dt>
              <dd className="text-xs text-tertiary-100 lg:text-sm">
                {stat.label}
              </dd>
            </div>
          ))}
        </dl>
      </Container>
    </Section>
  );
}
